// Package payload generates the synthetic inputs the fixture archives are
// written from. Every generator is seeded, so every host in a fleet builds
// the same bytes and no fixture byte is ever shipped or committed.
//
// The text payload is a byte-for-byte port of lzma-turbo's `cargo xtask
// fixtures` payload (SplitMix64, seed 7, a vocabulary of hex words mixed with
// random runs), so a 1 GiB payload here is the same `payload.bin` the
// lzma-turbo and earlier sevenz-turbo numbers were taken on.
package payload

import (
	"bufio"
	"encoding/binary"
	"fmt"
	"io"
	"math"
)

// MiB is a mebibyte.
const MiB = 1 << 20

// Rng is SplitMix64, the generator lzma-turbo's xtask uses. Test data only.
type Rng struct{ state uint64 }

// NewRng seeds a generator.
func NewRng(seed uint64) *Rng { return &Rng{state: seed} }

// Next returns the next 64-bit value.
func (r *Rng) Next() uint64 {
	r.state += 0x9E3779B97F4A7C15
	z := r.state
	z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9
	z = (z ^ (z >> 27)) * 0x94D049BB133111EB
	return z ^ (z >> 31)
}

// Range is uniform in low..=high.
func (r *Rng) Range(low, high int) int {
	return low + int(r.Next()%uint64(high-low+1))
}

// Chance is true with probability percent in a hundred.
func (r *Rng) Chance(percent uint64) bool { return r.Next()%100 < percent }

// Fill appends n generated bytes to out.
func (r *Rng) Fill(out []byte, n int) []byte {
	end := len(out) + n
	var word [8]byte
	for len(out) < end {
		binary.LittleEndian.PutUint64(word[:], r.Next())
		take := min(8, end-len(out))
		out = append(out, word[:take]...)
	}
	return out
}

// WriteText writes `mib` MiB of lzma-turbo's semi-compressible payload: a
// vocabulary of 4000 hex words mixed with runs of random bytes, built in
// 1 MiB chunks. The first N MiB of a larger payload are the N MiB payload.
func WriteText(w io.Writer, mib int) error {
	rng := NewRng(7)
	words := make([][]byte, 4000)
	for i := range words {
		raw := rng.Fill(nil, rng.Range(3, 9))
		words[i] = []byte(fmt.Sprintf("%x", raw))
	}
	out := bufio.NewWriterSize(w, MiB)
	chunk := make([]byte, 0, MiB+512)
	for range mib {
		chunk = chunk[:0]
		for len(chunk) < MiB {
			if rng.Chance(70) {
				word := rng.Range(0, len(words)-1)
				chunk = append(chunk, words[word]...)
				chunk = append(chunk, ' ')
			} else {
				chunk = rng.Fill(chunk, rng.Range(16, 256))
			}
		}
		if _, err := out.Write(chunk[:MiB]); err != nil {
			return err
		}
	}
	return out.Flush()
}

// WriteCodeX86 writes `bytes` of synthetic x86-64-shaped machine code for the
// BCJ and BCJ2 filters: instruction-like byte sequences from a fixed
// vocabulary, with dense E8 (CALL rel32) and E9 (JMP rel32) instructions
// whose targets are a few hundred functions. The x86 filter turns those
// relative displacements into absolute addresses, which repeat, which is
// what the filter is for; it is generated rather than collected from a build
// tree so that every architecture in a fleet filters the same bytes.
func WriteCodeX86(w io.Writer, bytes int64) error {
	rng := NewRng(0x86)
	vocabulary := make([][]byte, 384)
	for i := range vocabulary {
		vocabulary[i] = rng.Fill(nil, rng.Range(1, 7))
		// Keep the vocabulary itself free of branch opcodes, so the only
		// E8/E9 bytes are the instructions written below.
		for j, b := range vocabulary[i] {
			if b == 0xE8 || b == 0xE9 || b == 0x0F {
				vocabulary[i][j] = b ^ 0x40
			}
		}
	}
	functions := make([]int64, 512)
	for i := range functions {
		functions[i] = int64(rng.Range(0, int(min(bytes, math.MaxInt32))))
	}
	out := bufio.NewWriterSize(w, MiB)
	var position int64
	var rel [4]byte
	for position < bytes {
		var piece []byte
		if rng.Chance(12) {
			opcode := byte(0xE8)
			if rng.Chance(25) {
				opcode = 0xE9
			}
			target := functions[rng.Range(0, len(functions)-1)]
			binary.LittleEndian.PutUint32(rel[:], uint32(int32(target-(position+5))))
			piece = append([]byte{opcode}, rel[:]...)
		} else {
			piece = vocabulary[rng.Range(0, len(vocabulary)-1)]
		}
		if remaining := bytes - position; int64(len(piece)) > remaining {
			piece = piece[:remaining]
		}
		if _, err := out.Write(piece); err != nil {
			return err
		}
		position += int64(len(piece))
	}
	return out.Flush()
}

// WriteCodeARM64 writes `bytes` (rounded down to whole instructions) of
// synthetic AArch64-shaped code for the ARM64 BCJ filter: 4-byte words from a
// fixed vocabulary, with dense BL instructions whose targets are a few
// hundred functions.
func WriteCodeARM64(w io.Writer, bytes int64) error {
	rng := NewRng(0xA64)
	vocabulary := make([]uint32, 1024)
	for i := range vocabulary {
		word := uint32(rng.Next())
		// No accidental BL/B in the vocabulary (top six bits 100101/000101).
		if word>>26 == 0x25 || word>>26 == 0x05 {
			word ^= 0x40000000
		}
		vocabulary[i] = word
	}
	instructions := bytes / 4
	functions := make([]int64, 512)
	for i := range functions {
		functions[i] = int64(rng.Range(0, int(min(instructions, math.MaxInt32))))
	}
	out := bufio.NewWriterSize(w, MiB)
	var word [4]byte
	for index := range instructions {
		value := vocabulary[rng.Range(0, len(vocabulary)-1)]
		if rng.Chance(10) {
			offset := functions[rng.Range(0, len(functions)-1)] - index
			value = 0x94000000 | (uint32(int32(offset)) & 0x03FFFFFF)
		}
		binary.LittleEndian.PutUint32(word[:], value)
		if _, err := out.Write(word[:]); err != nil {
			return err
		}
	}
	return out.Flush()
}

// WriteAudio writes `bytes` (rounded down to whole frames) of synthetic
// 16-bit stereo PCM — two slowly drifting tones plus a little noise — which is
// the shape the 7z delta filter at distance 4 is for.
func WriteAudio(w io.Writer, bytes int64) error {
	rng := NewRng(0xDE17A)
	out := bufio.NewWriterSize(w, MiB)
	frames := bytes / 4
	var frame [4]byte
	for index := range frames {
		t := float64(index) / 44100
		left := 9000*math.Sin(2*math.Pi*220*t) + 3000*math.Sin(2*math.Pi*331*t+0.5)
		right := 9000*math.Sin(2*math.Pi*247*t+1) + 2500*math.Sin(2*math.Pi*370*t)
		noiseL := float64(int(rng.Next()%64) - 32)
		noiseR := float64(int(rng.Next()%64) - 32)
		binary.LittleEndian.PutUint16(frame[0:], uint16(int16(left+noiseL)))
		binary.LittleEndian.PutUint16(frame[2:], uint16(int16(right+noiseR)))
		if _, err := out.Write(frame[:]); err != nil {
			return err
		}
	}
	return out.Flush()
}

// TreeFile is one member of a generated tree.
type TreeFile struct {
	Path string
	Size int64
}

// Invented directory and file name parts for generated trees.
var (
	treeDirs  = []string{"aurora-ledger", "bramble-notes", "cinder-atlas", "dovetail-logs", "ember-index", "fable-drafts", "granite-sheets", "harbor-maps"}
	treeWords = []string{"quill", "lantern", "meadow", "copper", "willow", "saffron", "tundra", "orchid", "pebble", "zephyr", "marrow", "juniper"}
)

// Tree lays out `files` members whose sizes average `average` bytes (between
// a quarter of it and twice it), spread over invented directories. The
// layout is a function of its arguments only.
func Tree(files int, average int64, seed uint64) []TreeFile {
	rng := NewRng(seed)
	out := make([]TreeFile, 0, files)
	low, high := max(int(average/4), 1), int(average*7/4)
	for index := range files {
		dir := treeDirs[index%len(treeDirs)]
		word := treeWords[rng.Range(0, len(treeWords)-1)]
		out = append(out, TreeFile{
			Path: fmt.Sprintf("%s/%05d-%s.txt", dir, index, word),
			Size: int64(rng.Range(low, high)),
		})
	}
	return out
}

// WriteTreeFile writes one tree member's contents: text-payload-shaped bytes
// seeded by the member's index, so members differ from one another and a
// solid archive has something to find across them.
func WriteTreeFile(w io.Writer, index int, size int64) error {
	rng := NewRng(0x7EE + uint64(index))
	out := bufio.NewWriterSize(w, 64<<10)
	words := []string{"ledger", "quill", "aurora", "meadow", "copper", "lantern", "entry", "total", "note", "draft"}
	var written int64
	buf := make([]byte, 0, 512)
	for written < size {
		buf = buf[:0]
		if rng.Chance(80) {
			buf = append(buf, words[rng.Range(0, len(words)-1)]...)
			buf = fmt.Appendf(buf, " %d\n", rng.Range(0, 99999))
		} else {
			buf = rng.Fill(buf, rng.Range(8, 64))
		}
		if remaining := size - written; int64(len(buf)) > remaining {
			buf = buf[:remaining]
		}
		if _, err := out.Write(buf); err != nil {
			return err
		}
		written += int64(len(buf))
	}
	return out.Flush()
}
